### ISSUE TITLE
No response after signing in with metamask 

### ISSUE THREAD

**Issue by jveer634** [avneesh0612/DAO-tutorial#1]
### Description

I have got no response from the webpage after signing in with the metamask. I have actually clicked on the Sign in button, and the metamask didn't ask permission to connect but connected directly to the website. Even then after the screen did not change. I have attached the screenshot for reference.

#### Steps to reproduce
- Download the project
- run `npm i`
- run `npm run dev`
- open `localhost:3000` in browser 
- Click on `Sign in using Metamask`

### Screenshots

![image](https://user-images.githubusercontent.com/47923507/157788303-c8708ebd-3b5e-4807-a982-60a2df81d4ec.png)

**Comment by avneesh0612** [comment]
Hey, this is for a tutorial and I didn't wanna make it more complex so I didn't add a switch network feature but you can just switch to rinkeby and it would work :)

**Comment by jveer634** [comment]
So, I guess it would be better if you mention it on the homepage.. `Switch to the Rinkeby Network`

**Comment by avneesh0612** [comment]
hmm yeah, will write use Rinkeby
